### ISSUE TITLE
Why use output of decoder rather than hidden state of decoder when calculating attention?

### ISSUE THREAD

**Issue by nijianmo** [IBM/pytorch-seq2seq#114]
Thank you for the great job! It really helps a lot for me to catch up with pytorch implementation of seq2seq models. 

I have one question regarding the attention module. In many of the original papers, they all use hidden state of decoder to interact with the output of encoder. However in your implementation, it uses output of decoder instead. Do you have any reason not to follow the original paper? On the other hand, have you done experiments to check the difference between the current implementation and the original ones? 

Thanks!

```
    def forward_step(self, input_var, hidden, encoder_outputs, function):
        batch_size = input_var.size(0)
        output_size = input_var.size(1)
        embedded = self.embedding(input_var)
        embedded = self.input_dropout(embedded)

        output, hidden = self.rnn(embedded, hidden)

        attn = None
        if self.use_attention:
            output, attn = self.attention(output, encoder_outputs)
```

**Comment by kylegao91** [comment]
As far as I know, in the return values of rnn module, `output` contains `(h_1, h_2, ..., h_n)` and `hidden` contains the last hidden state `h_n`.  When the input length is 1, the two variables are equal.

The function name `forward_step` might be misleading because it sometimes forward an input with length longer than 1, and in that case we want to get the attentive hidden vectors for all the hidden states.

**Comment by nijianmo** [comment]
I see, thanks for the explanation!
